language: node_js
node_js:
  - 11.6.0
cache: npm


install:
  - npm install
  
branches:
only:
  - test-ci
  
script:
  - docker pull matheushrproenca/as2
  - docker run -v $PWD/:/app/report/ matheushrproenca/as2

after_script:
stage: Static Application Security Testing
script:
  - pip install -r requirements.txt
  - pip install bandit
  - 'bandit -r app.py -f json -o bandit-output.json'
artifacts:
  when: always
  paths: [bandit-output.json]
allow_failure: true

  
after_success:

  - ls  
  - chmod +x final_report.sh
  - . final_report.sh
  
  - git init
  - git config user.name "Travis CI"
  - git config user.email "travis@travis.org"
  - git add cucumber_report.html
  - git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" main:gh-pages
  - echo $RESULT
  - bash ./telegram_notification.sh
